const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const nodes=new Map();class Element{constructor(){this.children=[];this.classList={add(){},remove(){},toggle(){}};this.style={};}replaceChildren(){this.children=[];}append(...x){this.children.push(...x);}setAttribute(){}}
const get=s=>{if(!nodes.has(s))nodes.set(s,new Element());return nodes.get(s);};
const timers=new Map();let id=0;
const c=vm.createContext({Mahjong:require('./engine.js'),document:{querySelector:get,querySelectorAll:()=>[],createElement:()=>new Element()},navigator:{},setTimeout:f=>{timers.set(++id,f);return id;},clearTimeout:i=>timers.delete(i),console});
const spoken=[];c.Defense=require('./defense.js');c.Coach=require('./coach.js');c.Sound={play(){},say(t){spoken.push(t);},tileName:t=>require('./sound.js').tileName(t),stop(){spoken.length=0;},setEnabled(){},isEnabled:()=>true};
vm.runInContext(fs.readFileSync('tiles.js','utf8'),c);
vm.runInContext(fs.readFileSync('app.js','utf8'),c);
get('#drawButton').onclick();assert.equal(get('#hand').children.length,17);assert.equal(get('#drawButton').disabled,true);
get('#askInput').value='這張安全嗎';get('#askForm').onsubmit({preventDefault(){}});assert.match(get('#askAnswer').textContent,/防守參考/);assert.match(get('#askAnswer').textContent,/不是放槍機率/);
get('#drawButton').onclick();assert.equal(get('#hand').children.length,17);
get('#hand').children[0].onclick();assert.equal(get('#hand').children.length,17);assert.equal(get('#discardButton').disabled,false);
get('#discardButton').onclick();assert.equal(get('#hand').children.length,16);assert.equal(get('#drawButton').disabled,true);
assert.ok(spoken.length);const spokenCount=spoken.length;vm.runInContext('render()',c);assert.equal(spoken.length,spokenCount,'Rendering must not repeat a call');
const stale=[...timers.values()][0];get('#resetButton').onclick();const afterReset=get('#wallCount').textContent;stale();assert.equal(get('#wallCount').textContent,afterReset);assert.equal(timers.size,0);
get('#drawButton').onclick();get('#hand').children[0].onclick();get('#discardButton').onclick();
while(timers.size||vm.runInContext('waiting()',c)){if(vm.runInContext('waiting()',c))get('#claimActions').children.at(-1).onclick();else{const [i,f]=timers.entries().next().value;timers.delete(i);f();}}
assert.equal(get('#drawButton').disabled,false);assert.equal(get('#hand').children.length,16);
vm.runInContext("game.hands[0]=[2,3,6,8,8,9,12,15,17,18,19,21,23,27,27,27,33];game.melds=[[],[],[],[]];game.rivers=[[30,31],[12,15],[1,5],[12,9]];game.turn=0;game.phase='discard';analyze();render();",c);
get('#hand').children[16].onclick();get('#askSelected').onclick();assert.match(get('#askAnswer').textContent,/並列/);assert.equal(get('#hand').children.length,17);
get('#askInput').value='打白板可以嗎';get('#askForm').onsubmit({preventDefault(){}});assert.match(get('#askAnswer').textContent,/19 張/);
get('#sortButton').onclick();assert.equal(get('#askSelected').disabled,true);assert.equal(get('#askAnswer').textContent,'');
vm.runInContext("game.phase='claim';game.pending={from:3,tile:27,decisions:{3:{type:'pass'}}};render();",c);
assert.match(get('#coachBody').children[1].textContent,/本次首選/);
assert.ok(get('#coachBody').children.some(e=>e.children.some(x=>/碰後打/.test(x.textContent||''))));
get('#askInput').value='碰好嗎';get('#askForm').onsubmit({preventDefault(){}});assert.match(get('#askAnswer').textContent,/碰後打/);
assert.equal(vm.runInContext('game.phase',c),'claim');
get('#resetButton').onclick();
vm.runInContext("game.hands[0]=[0,1,2,3,4,5,9,10,11,18,19,20,27,27,31,31];game.melds=[[],[],[],[]];game.rivers=[[],[],[],[2]];game.log=[{player:3,action:'discard',tile:2}];game.turn=0;game.phase='claim';game.pending={from:3,tile:2,decisions:{1:{type:'pass'},2:{type:'pass'},3:{type:'pass'}}};render();",c);
get('#claimActions').children.at(-1).onclick();
assert.equal(vm.runInContext('reviewTimeline.length',c),1);assert.equal(vm.runInContext('reviewTimeline[0].choice.type',c),'pass');
assert.match(vm.runInContext('resolutionText(reviewTimeline[0])',c),/全員略過/);
assert.ok(get('#reviewView .empty-review').children.some(x=>x.children.some(y=>/略過/.test(y.textContent||''))));
vm.runInContext("game.phase='claim';game.pending={from:3,tile:2,decisions:{1:{type:'pass'},2:{type:'pass'},3:{type:'pass'}}};render();",c);
get('#claimActions').children[0].onclick();assert.equal(vm.runInContext('reviewTimeline[1].choice.type',c),'chi');assert.match(vm.runInContext('resolutionText(reviewTimeline[1])',c),/已取得吃/);
get('#resetButton').onclick();assert.equal(vm.runInContext('reviewTimeline.length',c),0);
vm.runInContext("game.hands[0]=[0,1,2,3,4,5,9,10,11,18,19,20,27,27,27,31,31];game.turn=0;game.phase='discard';render();",c);
get('#winButton').onclick();assert.equal(get('#winButton').disabled,true);assert.equal(get('#drawButton').disabled,true);assert.equal(get('#discardButton').disabled,true);
console.log('PASS: real UI handlers, repeat draw, select/confirm, complete AI round, stale timer after reset and ended-game locks.');
